# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths:
      - '**'
      # ignore changes to github/workflows
      - '!.github/workflows/**'
      # activate GitHub Actions when this file is edited
      - '.github/workflows/node.js.yml'
      # ignore markdown
      - '!**.md'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x, 15.x]
        include:
          - os: ubuntu-latest
            copy_source: cp -r dist ../server/src/views
            test_server: npm run serve &; sleep 5; trap 'exit(0)' SIGINT; kill -SIGINT $(lsof -t -i:8080)
          - os: windows-latest
            copy_source: Copy-Item -Path "dist" -Destination "..\\server\\src\\views" --Recurse
            test_server: Start-Job { Set-Location $using:PWD; npm run serve }; Get-Job | Stop-Job

    steps:
    - name: Make git use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install packages (server)
      working-directory: ./server
      run: npm ci

    - name: Apply linting to package (server)
      working-directory: ./server
      run: npm run lint --if-present

    - name: Run tests (server)
      working-directory: ./server
      run: npm test

    - name: Install packages (client)
      working-directory: ./client
      run: npm ci

    - name: Apply linting to package (client)
      working-directory: ./client
      run: npm run lint --if-present

    - name: Build package (client)
      working-directory: ./client
      run: npm run build --if-present

    - name: Run tests (client)
      working-directory: ./client
      run: npm test

    - name: Copy built package to server
      working-directory: ./client
      run: ${{ matrix.copy_source }}

    - name: Test web app
      working-directory: ./server
      run: ${{ matrix.test_server }}
